toto_admin_toto:
    resource: "@TotoBundle/Resources/config/routing/toto.yml"
    prefix:   /admin/toto

toto_homepage:
    path:     /
    defaults: { _controller: TotoBundle:Default:index }

toto_show:
    path: toto/{token}
    defaults:
        _controller: TotoBundle:PublicToto:show