<?php

namespace Coyote\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByRole($role)
	{
		
		$repository = $this->getEntityManager()
        	->getRepository('CoyoteBaseBundle:User');
		
		$query = $repository->createQueryBuilder('u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"' . $role . '"%')
		    ->getQuery()
			;

		return $query->getResult();
		
	}
}