TotoBundle\Entity\Group:
    type: entity
    table: toto_group
    repositoryClass: TotoBundle\Repository\GroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        teams:
            targetEntity: Team
            mappedBy: group
            cascade:
                - persist
                - remove
    fields:
        name:
            type: string
            length: 255
            unique: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    lifecycleCallbacks:
        prePersist:
            - setCreatedAt
            - setUpdatedAt
        preUpdate:
            - setUpdatedAt