TotoBundle\Entity\Team:
    type: entity
    table: toto_team
    repositoryClass: TotoBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        group:
            targetEntity: Group
            inversedBy: teams
            joinColumn:
                name: group_id
                referencedColumnName: id
    fields:
        name:
            type: string
            length: 255
            unique: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    lifecycleCallbacks:
        prePersist:
            - setCreatedAt
            - setUpdatedAt
        preUpdate:
            - setUpdatedAt