# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            remember_me:
                key:      "%secret%"
                lifetime: 2592000 # 30 days in seconds
                path: /
                domain:  ~ # Defaults to the current domain from $_SERVER
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                path: /logout
                target: /
            anonymous: true
            switch_user:
              role: ROLE_SUPER_ADMIN
              parameter: _super_su
    access_control:
        - path: ^/admin
          role: ROLE_SUPER_ADMIN