<?php

namespace TotoBundle\Repository;

/**
 * TotoEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotoEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
